"use client";

import { useState, useCallback } from "react";
import TimeInput from "@/components/TimeInput";
import ReadingCard from "@/components/ReadingCard";
import ReadingHistory from "@/components/ReadingHistory";
import { analyzeTimestamp, NumerologyResult } from "@/lib/numerology";
import { saveReading } from "@/lib/supabase";
import { ReadingResponse } from "@/lib/types";

export default function Home() {
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");
  const [numerology, setNumerology] = useState<NumerologyResult | null>(null);
  const [reading, setReading] = useState<ReadingResponse | null>(null);
  const [copied, setCopied] = useState(false);
  const [historyRefresh, setHistoryRefresh] = useState(0);

  const handleTimeSubmit = useCallback(async (time: string) => {
    setIsLoading(true);
    setError("");
    setReading(null);

    try {
      // Calculate numerology
      const result = analyzeTimestamp(time);
      setNumerology(result);

      // Get AI reading
      const response = await fetch("/api/reading", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(result),
      });

      if (!response.ok) {
        const errData = await response.json();
        throw new Error(errData.error || "Failed to generate reading");
      }

      const readingData: ReadingResponse = await response.json();
      setReading(readingData);

      // Save to database
      const fullReadingText = `ESSENCE\n${readingData.essence}\n\nMESSAGE\n${readingData.message}\n\nINVITATION\n${readingData.invitation}`;

      await saveReading({
        input_time: time,
        core_number: result.coreNumber,
        element: result.element,
        reading_text: fullReadingText,
      });

      // Trigger history refresh
      setHistoryRefresh((prev) => prev + 1);
    } catch (err) {
      console.error("Error:", err);
      setError(err instanceof Error ? err.message : "Something went wrong");
    } finally {
      setIsLoading(false);
    }
  }, []);

  const handleCopy = useCallback(() => {
    if (!numerology || !reading) return;

    const text = `${numerology.inputTime} Reading

Core Number: ${numerology.coreNumber}${numerology.isMasterNumber ? " (Master Number)" : ""}
Element: ${numerology.element}

ESSENCE
${reading.essence}

MESSAGE
${reading.message}

INVITATION
${reading.invitation}

— Generated by Vyberology`;

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [numerology, reading]);

  const handleNewReading = () => {
    setNumerology(null);
    setReading(null);
    setError("");
  };

  return (
    <div className="min-h-screen py-8 px-4">
      <div className="max-w-lg mx-auto">
        {/* Header */}
        <header className="text-center mb-10">
          <h1 className="text-4xl font-bold gradient-text mb-2">Vyberology</h1>
          <p className="text-gray-400 text-lg">
            Decode your number synchronicities
          </p>
        </header>

        {/* Main content */}
        {!reading ? (
          <>
            <TimeInput onSubmit={handleTimeSubmit} isLoading={isLoading} />

            {error && (
              <div className="mt-6 p-4 bg-red-900/30 border border-red-800/50 rounded-xl text-center">
                <p className="text-red-300">{error}</p>
                <button
                  onClick={() => setError("")}
                  className="mt-2 text-sm text-red-400 hover:text-red-300 underline"
                >
                  Try again
                </button>
              </div>
            )}

            <ReadingHistory refreshTrigger={historyRefresh} />
          </>
        ) : (
          <>
            <ReadingCard
              numerology={numerology!}
              reading={reading}
              onCopy={handleCopy}
              copied={copied}
            />

            <div className="mt-6 text-center">
              <button
                onClick={handleNewReading}
                className="px-6 py-3 text-primary-400 hover:text-primary-300
                         transition-colors flex items-center gap-2 mx-auto"
              >
                <svg
                  className="w-5 h-5"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M12 6v6m0 0v6m0-6h6m-6 0H6"
                  />
                </svg>
                New Reading
              </button>
            </div>
          </>
        )}

        {/* Footer */}
        <footer className="mt-16 text-center text-gray-600 text-sm">
          <p>Protocol 69: Never take, always give back more</p>
          <p className="mt-1">
            Made with{" "}
            <span className="text-primary-500" aria-label="love">
              love
            </span>{" "}
            by HwinNwin Enterprises
          </p>
        </footer>
      </div>
    </div>
  );
}
