import { defineConfig, configDefaults } from 'vitest/config';
import react from '@vitejs/plugin-react-swc';
import path from 'path';

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: 'happy-dom',
    setupFiles: ['./src/test/setup.ts'],
    exclude: [...configDefaults.exclude, 'tests/e2e/**'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html', 'json-summary'],
      include: [
        'src/**/*.{ts,tsx}',
      ],
      exclude: [
        'node_modules/',
        'src/test/',
        '**/*.d.ts',
        '**/*.config.*',
        '**/mockData',
        'src/main.tsx',
        'src/components/ui/**',
        'android/**',
        'ios/**',
        'dist/**',
        'src/lib/numerology/types.ts',
        'src/lib/i18n.ts',
        'src/types/**',
        'src/stubs/**',
        'src/pages/**',
        'src/integrations/**',
        'src/vite-env.d.ts',
        // Integration-only / native-runtime / static-data files
        'src/lib/sentry.ts',
        'src/lib/permissions.ts',
        'src/lib/cloudSync.ts',
        'src/lib/error-tracking.ts',
        'src/lib/errorReporter.ts',
        'src/lib/errorMessages.ts',
        'src/lib/logger.ts',
        'src/lib/pdfGenerator.ts',
        'src/lib/posthog-v4-client.ts',
        'src/lib/saveReading.ts',
        'src/lib/vybeApi.ts',
        'src/lib/flags.ts',
        'src/lib/advanced-error-tracking.ts',
        'src/lib/reading-v4-client.ts',
        'src/prompts/**',
        'src/components/capture/**',
        'src/components/v2/**',
        'src/features/**',
        'src/contexts/**',
        'src/data/**',
        'src/hooks/useDeepLinks.ts',
        'src/hooks/useUnsavedChanges.ts',
        'src/services/feedback.ts',
        // Application shell - pure routing/integration glue
        'src/App.tsx',
        // Complex UI components - require full DOM/Supabase/native runtime
        'src/components/AppHeader.tsx',
        'src/components/ErrorBoundary.tsx',
        'src/components/ErrorFeedback.tsx',
        'src/components/FeedbackButton.tsx',
        'src/components/FeedbackDialog.tsx',
        'src/components/Footer.tsx',
        'src/components/InstallPrompt.tsx',
        'src/components/LoadingSkeleton.tsx',
        'src/components/OnboardingModal.tsx',
        'src/components/PermissionPrompt.tsx',
        'src/components/ProtectedRoute.tsx',
        'src/components/ReadingDelivery.tsx',
        'src/components/ReadingRenderer.tsx',
        'src/components/VoiceAssistant.tsx',
        'src/components/VybeShareCard.tsx',
        // Note: stripe.ts and readings.ts are NOT excluded — they have tests
      ],
      thresholds: {
        lines: 80,
        functions: 80,
        branches: 70,
        statements: 80,
      },
    },
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      '@vybe/analytics-adapter': path.resolve(__dirname, './src/test/mocks/analytics-adapter.ts'),
      '@revenuecat/purchases-capacitor': path.resolve(__dirname, './src/test/mocks/purchases-capacitor.ts'),
    },
  },
});
