# Netlify Configuration for Vyberology Web App
# Root level configuration for monorepo deployment

[build]
  # Base directory - where the web app lives
  base = "apps/web"
  # Build command - run from base directory
  command = "VITE_APP_ENV=production VITE_FEATURE_OCR=on VITE_FEATURE_PM_SENTRY=on VITE_SUPABASE_URL=https://agzvrpvuhoruiiugfkzc.supabase.co VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnenZycHZ1aG9ydWlpdWdma3pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMDg1MzksImV4cCI6MjA3NDY4NDUzOX0.QA7RJvgzc7jwwVKoFVfT8uePtdAlV6R5aVUXwVnRhNE VITE_V4_ENABLED=false npm run build"
  # Publish directory relative to base
  publish = "dist"
  # Ignore builds if no changes in these paths
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF apps/web packages/"

# Environment variables (also set these in Netlify UI for security)
[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

# Redirect subdomain to primary vyberology.com domain
[[redirects]]
  from = "https://vyberology.thevybe.global/*"
  to = "https://vyberology.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://vyberology.thevybe.global/*"
  to = "https://vyberology.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://vyberology.com/*"
  to = "https://vyberology.com/:splat"
  status = 301
  force = true

# Redirect store and online domains when configured
[[redirects]]
  from = "https://vyberology.store/*"
  to = "https://vyberology.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://vyberology.online/*"
  to = "https://vyberology.com/:splat"
  status = 301
  force = true

# SPA fallback - all routes should serve index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
