/**
 * VYBEROLOGY V2.0 - SAMPLE READINGS
 * Production-ready ReadingData examples generated by Lumen
 * For UI testing, share card validation, and engine integration
 */

import { ReadingData } from '../types';

// 🔥 SAMPLE 1 — FIRE (🜂) — Solar Plexus
export const sampleFireReading: ReadingData = {
  markerTitle: "Marker 144 — Ignited Momentum",
  resonanceText:
    "Your energy is rising with clarity and purpose. The path ahead feels charged, aligned, and ready for decisive action. Confidence stabilizes as you move from intention into embodiment.",
  essenceLine: "This is the moment to act with certainty.",
  intention: "Take one bold step today.",
  reflectionKey: "What decision feels aligned and unavoidable?",

  element: "fire",
  chakra: "solar",

  numbers: [1, 4, 4],
  masterNumbers: [],

  createdAt: new Date().toISOString(),
  version: "V2.0",
  source: "manual",
};

// 🜃 SAMPLE 2 — EARTH (🜃) — Heart
export const sampleEarthReading: ReadingData = {
  markerTitle: "Marker 42 — Stabilized Grounding",
  resonanceText:
    "You are anchoring into a deeper layer of stability. What once felt scattered is becoming structured. Your foundation is strengthening, allowing new clarity to emerge from within.",
  essenceLine: "Trust the ground that is forming beneath you.",
  intention: "Choose one stabilizing habit today.",
  reflectionKey: "Where does steadiness already exist in your body?",

  element: "earth",
  chakra: "heart",

  numbers: [4, 2],
  masterNumbers: [],

  createdAt: new Date().toISOString(),
  version: "V2.0",
  source: "manual",
};

// 🜁 SAMPLE 3 — AIR (🜁) — Third Eye
export const sampleAirReading: ReadingData = {
  markerTitle: "Marker 137 — Clarity Rising",
  resonanceText:
    "Your intuitive field is sharpening. Old mental fog is dissolving as higher insight becomes available. This is a time for perception over pressure, for vision over force.",
  essenceLine: "Let clarity guide the next step.",
  intention: "Clear your mental space before making decisions.",
  reflectionKey: "What truth is becoming impossible to ignore?",

  element: "air",
  chakra: "thirdEye",

  numbers: [1, 3, 7],
  masterNumbers: [],

  createdAt: new Date().toISOString(),
  version: "V2.0",
  source: "manual",
};

// 🜄 SAMPLE 4 — WATER (🜄) — Sacral
export const sampleWaterReading: ReadingData = {
  markerTitle: "Marker 27 — Emotional Flow",
  resonanceText:
    "Your emotional landscape is softening and becoming more navigable. Sensitivity becomes strength when allowed to move. This phase brings emotional clarity through gentle release.",
  essenceLine: "Let your feelings move without judgment.",
  intention: "Make space for one honest emotional check-in.",
  reflectionKey: "What emotion is asking to be acknowledged today?",

  element: "water",
  chakra: "sacral",

  numbers: [2, 7],
  masterNumbers: [],

  createdAt: new Date().toISOString(),
  version: "V2.0",
  source: "manual",
};

// 🔱 SAMPLE 5 — MASTER NUMBER 11 — Third Eye / Air
export const sampleMaster11Reading: ReadingData = {
  markerTitle: "Marker 11 — Signal of Alignment",
  resonanceText:
    "A higher message is coming through your intuitive field. The veil between thought and insight is thin right now. This is a moment of heightened perception, synchronicity, and inner guidance.",
  essenceLine: "Trust the signal — your intuition is online.",
  intention: "Honor the first intuitive hit you receive today.",
  reflectionKey: "What inner knowing feels unmistakably true?",

  element: "air",
  chakra: "thirdEye",

  numbers: [11],
  masterNumbers: [11],

  createdAt: new Date().toISOString(),
  version: "V2.0",
  source: "manual",
};

// All samples exported for easy selection
export const allSampleReadings = {
  fire: sampleFireReading,
  earth: sampleEarthReading,
  air: sampleAirReading,
  water: sampleWaterReading,
  master11: sampleMaster11Reading,
};

// Array format for iteration
export const sampleReadingsArray = [
  sampleFireReading,
  sampleEarthReading,
  sampleAirReading,
  sampleWaterReading,
  sampleMaster11Reading,
];
