import { serve } from "https://deno.land/std@0.168.0/http/server.ts"; // added by Lumen (Stage 4A PR1-DI)
import { buildCors, passesRateLimit } from "../_shared/security.ts"; // added by Lumen (Stage 4A PR1-DI)
import { prepareReadResult } from "./handler.ts"; // added by Lumen (Stage 4A PR1-DI)

serve(async (req) => { // added by Lumen (Stage 4A PR1-DI)
  const { headers, allowed } = buildCors(req.headers.get("origin")); // added by Lumen (Stage 4A PR1-DI)
  const jsonHeaders = { ...headers, "Content-Type": "application/json" }; // added by Lumen (Stage 4A PR1-DI)

  if (req.method === "OPTIONS") { // added by Lumen (Stage 4A PR1-DI)
    return new Response(null, { status: 204, headers }); // added by Lumen (Stage 4A PR1-DI)
  } // added by Lumen (Stage 4A PR1-DI)

  if (!allowed) { // added by Lumen (Stage 4A PR1-DI)
    return new Response(JSON.stringify({ error: "Origin not allowed" }), { status: 403, headers: jsonHeaders }); // added by Lumen (Stage 4A PR1-DI)
  } // added by Lumen (Stage 4A PR1-DI)

  if (!(await passesRateLimit(req, "read"))) { // added by Lumen (Stage 4A PR1-DI)
    return new Response( // added by Lumen (Stage 4A PR1-DI)
      JSON.stringify({ error: "Rate limit exceeded. Please try again shortly." }), // added by Lumen (Stage 4A PR1-DI)
      { status: 429, headers: jsonHeaders }, // added by Lumen (Stage 4A PR1-DI)
    ); // added by Lumen (Stage 4A PR1-DI)
  } // added by Lumen (Stage 4A PR1-DI)

  let payload: unknown; // added by Lumen (Stage 4A PR1-DI)
  try { // added by Lumen (Stage 4A PR1-DI)
    payload = await req.json(); // added by Lumen (Stage 4A PR1-DI)
  } catch { // added by Lumen (Stage 4A PR1-DI)
    return new Response(JSON.stringify({ error: "Invalid JSON payload" }), { status: 400, headers: jsonHeaders }); // added by Lumen (Stage 4A PR1-DI)
  } // added by Lumen (Stage 4A PR1-DI)

  try { // added by Lumen (Stage 4A PR1-DI)
    const result = prepareReadResult(payload); // added by Lumen (Stage 4A PR1-DI)
    if (!result.ok) { // added by Lumen (Stage 4A PR1-DI)
      return new Response(JSON.stringify({ error: result.error.message }), { status: 400, headers: jsonHeaders }); // added by Lumen (Stage 4A PR1-DI)
    } // added by Lumen (Stage 4A PR1-DI)

    return new Response(JSON.stringify(result.value), { status: 200, headers: jsonHeaders }); // added by Lumen (Stage 4A PR1-DI)
  } catch (error) { // added by Lumen (Stage 4A PR1-DI)
    console.error("Error:", error); // added by Lumen (Stage 4A PR1-DI)
    const message = error instanceof Error ? error.message : "Unknown error occurred"; // added by Lumen (Stage 4A PR1-DI)
    return new Response(JSON.stringify({ error: message }), { status: 500, headers: jsonHeaders }); // added by Lumen (Stage 4A PR1-DI)
  } // added by Lumen (Stage 4A PR1-DI)
}); // added by Lumen (Stage 4A PR1-DI)
