"use client";

import { NumerologyResult, ELEMENT_INFO, NUMBER_MEANINGS } from "@/lib/types";
import { detectPatterns } from "@/lib/numerology";
import ShareButton from "./ShareButton";

interface ReadingCardProps {
  numerology: NumerologyResult;
  reading: {
    essence: string;
    message: string;
    invitation: string;
  };
  onCopy: () => void;
  copied: boolean;
}

export default function ReadingCard({
  numerology,
  reading,
  onCopy,
  copied,
}: ReadingCardProps) {
  const elementInfo = ELEMENT_INFO[numerology.element];
  const patterns = detectPatterns(numerology.inputTime);
  const numberMeaning = NUMBER_MEANINGS[numerology.coreNumber] || "";

  const fullReadingText = `✨ ${numerology.inputTime} Reading

Core Number: ${numerology.coreNumber}${numerology.isMasterNumber ? " (Master Number)" : ""}
Element: ${elementInfo.emoji} ${elementInfo.name.charAt(0).toUpperCase() + elementInfo.name.slice(1)}

ESSENCE
${reading.essence}

MESSAGE
${reading.message}

INVITATION
${reading.invitation}

— Generated by Vyberology`;

  return (
    <div className="w-full max-w-md mx-auto animate-fade-in">
      <div className="bg-gradient-to-br from-gray-900 to-gray-950 rounded-2xl border border-primary-800/30 overflow-hidden shadow-xl shadow-primary-900/20">
        {/* Header with time and core number */}
        <div className="bg-gradient-to-r from-primary-900/50 to-primary-800/30 px-6 py-5 border-b border-primary-800/30">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-gray-400 text-sm">Your synchronicity</p>
              <p className="text-4xl font-mono font-bold text-white mt-1">
                {numerology.inputTime}
              </p>
              {patterns.length > 0 && (
                <div className="flex gap-2 mt-2">
                  {patterns.map((pattern) => (
                    <span
                      key={pattern}
                      className="text-xs px-2 py-1 bg-primary-800/50 text-primary-300 rounded-full"
                    >
                      {pattern}
                    </span>
                  ))}
                </div>
              )}
            </div>
            <div className="text-right">
              <div
                className={`text-5xl font-bold ${
                  numerology.isMasterNumber
                    ? "text-yellow-400"
                    : "text-primary-400"
                }`}
              >
                {numerology.coreNumber}
              </div>
              {numerology.isMasterNumber && (
                <span className="text-xs text-yellow-400/80 font-medium">
                  Master Number
                </span>
              )}
            </div>
          </div>
        </div>

        {/* Element and number meaning */}
        <div className="px-6 py-4 border-b border-gray-800/50">
          <div className="flex items-center gap-3">
            <span className="text-3xl">{elementInfo.emoji}</span>
            <div>
              <p className={`font-semibold capitalize ${elementInfo.color}`}>
                {elementInfo.name} Element
              </p>
              <p className="text-gray-400 text-sm">
                {elementInfo.qualities.join(" • ")}
              </p>
            </div>
          </div>
          <p className="mt-3 text-gray-300 text-sm italic">{numberMeaning}</p>
        </div>

        {/* Reading sections */}
        <div className="px-6 py-5 space-y-5">
          <div className="animate-slide-up" style={{ animationDelay: "0.1s" }}>
            <h3 className="text-primary-400 font-semibold text-sm uppercase tracking-wider mb-2">
              Essence
            </h3>
            <p className="text-gray-200 leading-relaxed">{reading.essence}</p>
          </div>

          <div className="animate-slide-up" style={{ animationDelay: "0.2s" }}>
            <h3 className="text-primary-400 font-semibold text-sm uppercase tracking-wider mb-2">
              Message
            </h3>
            <p className="text-gray-200 leading-relaxed">{reading.message}</p>
          </div>

          <div className="animate-slide-up" style={{ animationDelay: "0.3s" }}>
            <h3 className="text-primary-400 font-semibold text-sm uppercase tracking-wider mb-2">
              Invitation
            </h3>
            <p className="text-gray-200 leading-relaxed font-medium">
              {reading.invitation}
            </p>
          </div>
        </div>

        {/* Action buttons */}
        <div className="px-6 py-4 bg-gray-900/50 border-t border-gray-800/50 flex gap-3">
          <button
            onClick={onCopy}
            className="flex-1 px-4 py-2.5 bg-gray-800 hover:bg-gray-700
                     text-white font-medium rounded-xl border border-gray-700
                     transition-all flex items-center justify-center gap-2"
          >
            {copied ? (
              <>
                <svg
                  className="w-5 h-5 text-green-400"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M5 13l4 4L19 7"
                  />
                </svg>
                Copied!
              </>
            ) : (
              <>
                <svg
                  className="w-5 h-5"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3"
                  />
                </svg>
                Copy
              </>
            )}
          </button>
          <ShareButton
            title={`${numerology.inputTime} Reading`}
            text={fullReadingText}
          />
        </div>
      </div>
    </div>
  );
}
