[build]
  command = ""
  publish = "."

[[redirects]]
  from = "https://vyberology.thevybe.global/*"
  to = "https://vyberology.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
