const JSON_HEADERS = { "Content-Type": "application/json" } as const; // added by Lumen (Stage 4A PR1-DI)

export type Result<T, E> = { ok: true; value: T } | { ok: false; error: E }; // added by Lumen (Stage 4A PR1-DI)

export type ReadingErr = // added by Lumen (Stage 4A PR1-DI)
  | { code: "UNAUTHORIZED"; message: string } // added by Lumen (Stage 4A PR1-DI)
  | { code: "BAD_REQUEST"; message: string } // added by Lumen (Stage 4A PR1-DI)
  | { code: "ENGINE_ERROR"; message: string }; // added by Lumen (Stage 4A PR1-DI)

export interface ReadingPayload { // added by Lumen (Stage 4A PR1-DI)
  input_text: string; // added by Lumen (Stage 4A PR1-DI)
  context?: unknown; // added by Lumen (Stage 4A PR1-DI)
  tags?: unknown; // added by Lumen (Stage 4A PR1-DI)
} // added by Lumen (Stage 4A PR1-DI)

export interface ReadingOk { // added by Lumen (Stage 4A PR1-DI)
  input_text: string; // added by Lumen (Stage 4A PR1-DI)
  normalized_number: string; // added by Lumen (Stage 4A PR1-DI)
  numerology_data: NumerologyEntry; // added by Lumen (Stage 4A PR1-DI)
  chakra_data: ChakraEntry; // added by Lumen (Stage 4A PR1-DI)
} // added by Lumen (Stage 4A PR1-DI)

export interface Deps { // added by Lumen (Stage 4A PR1-DI)
  requireJwtHeader: (req: Request) => { ok: true; token: string } | { ok: false }; // added by Lumen (Stage 4A PR1-DI)
  ensureSupabaseClient: () => unknown; // added by Lumen (Stage 4A PR1-DI)
} // added by Lumen (Stage 4A PR1-DI)

interface NumerologyEntry { // added by Lumen (Stage 4A PR1-DI)
  headline: string; // added by Lumen (Stage 4A PR1-DI)
  keywords: string[]; // added by Lumen (Stage 4A PR1-DI)
  guidance: string; // added by Lumen (Stage 4A PR1-DI)
} // added by Lumen (Stage 4A PR1-DI)

interface ChakraEntry { // added by Lumen (Stage 4A PR1-DI)
  name: string; // added by Lumen (Stage 4A PR1-DI)
  element: string; // added by Lumen (Stage 4A PR1-DI)
  focus: string; // added by Lumen (Stage 4A PR1-DI)
  color: string; // added by Lumen (Stage 4A PR1-DI)
  amplified?: boolean; // added by Lumen (Stage 4A PR1-DI)
  message?: string; // added by Lumen (Stage 4A PR1-DI)
} // added by Lumen (Stage 4A PR1-DI)

const NUMEROLOGY_MAP: Record<string, NumerologyEntry> = { // added by Lumen (Stage 4A PR1-DI)
  "0": { // added by Lumen (Stage 4A PR1-DI)
    headline: "Divine Zero", // added by Lumen (Stage 4A PR1-DI)
    keywords: ["infinite potential", "reset", "source", "void", "beginning"], // added by Lumen (Stage 4A PR1-DI)
    guidance: "You stand at the threshold of infinite possibility. The zero represents the cosmic womb from which all creation emerges.", // added by Lumen (Stage 4A PR1-DI)
  }, // added by Lumen (Stage 4A PR1-DI)
  "1": { // added by Lumen (Stage 4A PR1-DI)
    headline: "The Initiator", // added by Lumen (Stage 4A PR1-DI)
    keywords: ["new beginning", "leadership", "independence", "confidence"], // added by Lumen (Stage 4A PR1-DI)
    guidance: "You are being called to step forward and lead. This is your moment to initiate and create.", // added by Lumen (Stage 4A PR1-DI)
  }, // added by Lumen (Stage 4A PR1-DI)
  "2": { // added by Lumen (Stage 4A PR1-DI)
    headline: "The Harmonizer", // added by Lumen (Stage 4A PR1-DI)
    keywords: ["balance", "cooperation", "partnership", "diplomacy"], // added by Lumen (Stage 4A PR1-DI)
    guidance: "Seek harmony and balance. Partnerships and collaboration will bring success.", // added by Lumen (Stage 4A PR1-DI)
  }, // added by Lumen (Stage 4A PR1-DI)
  "3": { // added by Lumen (Stage 4A PR1-DI)
    headline: "The Creator", // added by Lumen (Stage 4A PR1-DI)
    keywords: ["joy", "expression", "creativity", "communication"], // added by Lumen (Stage 4A PR1-DI)
    guidance: "Express yourself freely. Your creative energy is flowing and wants to be shared.", // added by Lumen (Stage 4A PR1-DI)
  }, // added by Lumen (Stage 4A PR1-DI)
  "4": { // added by Lumen (Stage 4A PR1-DI)
    headline: "The Builder", // added by Lumen (Stage 4A PR1-DI)
    keywords: ["structure", "foundation", "stability", "discipline"], // added by Lumen (Stage 4A PR1-DI)
    guidance: "Build solid foundations. Focus on practical matters and creating lasting structures.", // added by Lumen (Stage 4A PR1-DI)
  }, // added by Lumen (Stage 4A PR1-DI)
  "5": { // added by Lumen (Stage 4A PR1-DI)
    headline: "Freedom Seeker", // added by Lumen (Stage 4A PR1-DI)
    keywords: ["change", "adapt", "freedom", "adventure"], // added by Lumen (Stage 4A PR1-DI)
    guidance: "Embrace change and new experiences. Freedom comes through adaptability.", // added by Lumen (Stage 4A PR1-DI)
  }, // added by Lumen (Stage 4A PR1-DI)
  "6": { // added by Lumen (Stage 4A PR1-DI)
    headline: "The Nurturer", // added by Lumen (Stage 4A PR1-DI)
    keywords: ["care", "harmony", "responsibility", "service"], // added by Lumen (Stage 4A PR1-DI)
    guidance: "Care for yourself and others. Create harmony in your relationships and environment.", // added by Lumen (Stage 4A PR1-DI)
  }, // added by Lumen (Stage 4A PR1-DI)
  "7": { // added by Lumen (Stage 4A PR1-DI)
    headline: "The Seeker", // added by Lumen (Stage 4A PR1-DI)
    keywords: ["wisdom", "spirit", "introspection", "truth"], // added by Lumen (Stage 4A PR1-DI)
    guidance: "Seek deeper understanding. Trust your inner wisdom and spiritual insights.", // added by Lumen (Stage 4A PR1-DI)
  }, // added by Lumen (Stage 4A PR1-DI)
  "8": { // added by Lumen (Stage 4A PR1-DI)
    headline: "The Powerhouse", // added by Lumen (Stage 4A PR1-DI)
    keywords: ["abundance", "authority", "power", "manifestation"], // added by Lumen (Stage 4A PR1-DI)
    guidance: "Step into your power. Abundance and success are within your reach.", // added by Lumen (Stage 4A PR1-DI)
  }, // added by Lumen (Stage 4A PR1-DI)
  "9": { // added by Lumen (Stage 4A PR1-DI)
    headline: "The Humanitarian", // added by Lumen (Stage 4A PR1-DI)
    keywords: ["completion", "legacy", "wisdom", "service"], // added by Lumen (Stage 4A PR1-DI)
    guidance: "A cycle is completing. Share your wisdom and create a lasting legacy.", // added by Lumen (Stage 4A PR1-DI)
  }, // added by Lumen (Stage 4A PR1-DI)
  "11": { // added by Lumen (Stage 4A PR1-DI)
    headline: "The Visionary", // added by Lumen (Stage 4A PR1-DI)
    keywords: ["intuition", "downloads", "spiritual insight", "illumination"], // added by Lumen (Stage 4A PR1-DI)
    guidance: "You are receiving divine downloads. Trust your heightened intuition and inner visions.", // added by Lumen (Stage 4A PR1-DI)
  }, // added by Lumen (Stage 4A PR1-DI)
  "22": { // added by Lumen (Stage 4A PR1-DI)
    headline: "The Master Builder", // added by Lumen (Stage 4A PR1-DI)
    keywords: ["architecture", "legacy", "manifestation", "grand vision"], // added by Lumen (Stage 4A PR1-DI)
    guidance: "You have the power to build something lasting and significant. Think big and act strategically.", // added by Lumen (Stage 4A PR1-DI)
  }, // added by Lumen (Stage 4A PR1-DI)
  "33": { // added by Lumen (Stage 4A PR1-DI)
    headline: "The Master Teacher", // added by Lumen (Stage 4A PR1-DI)
    keywords: ["love", "healing", "compassion", "guidance"], // added by Lumen (Stage 4A PR1-DI)
    guidance: "You are here to heal and teach through unconditional love. Share your gifts with the world.", // added by Lumen (Stage 4A PR1-DI)
  }, // added by Lumen (Stage 4A PR1-DI)
  "44": { // added by Lumen (Stage 4A PR1-DI)
    headline: "The Master Organizer", // added by Lumen (Stage 4A PR1-DI)
    keywords: ["systems", "empire", "discipline", "mastery"], // added by Lumen (Stage 4A PR1-DI)
    guidance: "Build powerful systems and structures. Your organizational mastery can create an empire.", // added by Lumen (Stage 4A PR1-DI)
  }, // added by Lumen (Stage 4A PR1-DI)
}; // added by Lumen (Stage 4A PR1-DI)

const CHAKRA_MAP: Record<string, ChakraEntry> = { // added by Lumen (Stage 4A PR1-DI)
  "1": { name: "Root Chakra", element: "Earth", focus: "grounding, survival, security", color: "red" }, // added by Lumen (Stage 4A PR1-DI)
  "2": { name: "Sacral Chakra", element: "Water", focus: "creativity, emotion, sensuality", color: "orange" }, // added by Lumen (Stage 4A PR1-DI)
  "3": { name: "Solar Plexus Chakra", element: "Fire", focus: "power, confidence, action", color: "yellow" }, // added by Lumen (Stage 4A PR1-DI)
  "4": { name: "Heart Chakra", element: "Air", focus: "love, compassion, connection", color: "green" }, // added by Lumen (Stage 4A PR1-DI)
  "5": { name: "Throat Chakra", element: "Sound", focus: "communication, truth, expression", color: "blue" }, // added by Lumen (Stage 4A PR1-DI)
  "6": { name: "Third Eye Chakra", element: "Light", focus: "intuition, vision, insight", color: "indigo" }, // added by Lumen (Stage 4A PR1-DI)
  "7": { name: "Crown Chakra", element: "Thought", focus: "consciousness, unity, enlightenment", color: "violet" }, // added by Lumen (Stage 4A PR1-DI)
  "8": { name: "Earth Star Chakra", element: "Earth", focus: "connection to Earth, ancestors, lineage", color: "brown" }, // added by Lumen (Stage 4A PR1-DI)
  "9": { name: "Soul Star Chakra", element: "Spirit", focus: "divine purpose, cosmic connection, higher self", color: "white" }, // added by Lumen (Stage 4A PR1-DI)
}; // added by Lumen (Stage 4A PR1-DI)

function makeAmplifiedChakra(core: string, message: string): ChakraEntry { // added by Lumen (Stage 4A PR1-DI)
  const base = CHAKRA_MAP[core] ?? CHAKRA_MAP["1"]; // added by Lumen (Stage 4A PR1-DI)
  return { ...base, amplified: true, message }; // added by Lumen (Stage 4A PR1-DI)
} // added by Lumen (Stage 4A PR1-DI)

const MASTER_AMPLIFICATIONS: Record<string, ChakraEntry> = { // added by Lumen (Stage 4A PR1-DI)
  "11": makeAmplifiedChakra("7", "Crown chakra amplified - heightened spiritual connection"), // added by Lumen (Stage 4A PR1-DI)
  "22": makeAmplifiedChakra("1", "Root chakra amplified - master manifestation energy"), // added by Lumen (Stage 4A PR1-DI)
  "33": makeAmplifiedChakra("4", "Heart chakra amplified - master healing energy"), // added by Lumen (Stage 4A PR1-DI)
  "44": makeAmplifiedChakra("8", "Earth Star amplified - master grounding energy"), // added by Lumen (Stage 4A PR1-DI)
}; // added by Lumen (Stage 4A PR1-DI)

const MASTER_NUMBERS = new Set([11, 22, 33, 44]); // added by Lumen (Stage 4A PR1-DI)

function reduceToCoreNumber(input: string): string { // added by Lumen (Stage 4A PR1-DI)
  let total = parseInt(input, 10); // added by Lumen (Stage 4A PR1-DI)
  while (total > 9 && !MASTER_NUMBERS.has(total)) { // added by Lumen (Stage 4A PR1-DI)
    total = String(total) // added by Lumen (Stage 4A PR1-DI)
      .split("") // added by Lumen (Stage 4A PR1-DI)
      .reduce((acc, digit) => acc + Number(digit), 0); // added by Lumen (Stage 4A PR1-DI)
  } // added by Lumen (Stage 4A PR1-DI)
  return String(total); // added by Lumen (Stage 4A PR1-DI)
} // added by Lumen (Stage 4A PR1-DI)

function normalizeNumber(raw: string): string { // added by Lumen (Stage 4A PR1-DI)
  const cleaned = raw.replace(/[^\d:%]/g, ""); // added by Lumen (Stage 4A PR1-DI)
  const digits = cleaned.replace(/[:%]/g, ""); // added by Lumen (Stage 4A PR1-DI)
  if (!digits) { // added by Lumen (Stage 4A PR1-DI)
    return "0"; // added by Lumen (Stage 4A PR1-DI)
  } // added by Lumen (Stage 4A PR1-DI)
  return reduceToCoreNumber(digits); // added by Lumen (Stage 4A PR1-DI)
} // added by Lumen (Stage 4A PR1-DI)

function getNumerologyMeaning(core: string): NumerologyEntry { // added by Lumen (Stage 4A PR1-DI)
  return NUMEROLOGY_MAP[core] ?? NUMEROLOGY_MAP["0"]; // added by Lumen (Stage 4A PR1-DI)
} // added by Lumen (Stage 4A PR1-DI)

function getChakraMeaning(core: string): ChakraEntry { // added by Lumen (Stage 4A PR1-DI)
  if (MASTER_AMPLIFICATIONS[core]) { // added by Lumen (Stage 4A PR1-DI)
    return MASTER_AMPLIFICATIONS[core]; // added by Lumen (Stage 4A PR1-DI)
  } // added by Lumen (Stage 4A PR1-DI)
  return CHAKRA_MAP[core] ?? CHAKRA_MAP["1"]; // added by Lumen (Stage 4A PR1-DI)
} // added by Lumen (Stage 4A PR1-DI)

function buildReading(payload: ReadingPayload): ReadingOk { // added by Lumen (Stage 4A PR1-DI)
  const normalized = normalizeNumber(payload.input_text); // added by Lumen (Stage 4A PR1-DI)
  const numerology = getNumerologyMeaning(normalized); // added by Lumen (Stage 4A PR1-DI)
  const chakra = getChakraMeaning(normalized); // added by Lumen (Stage 4A PR1-DI)
  return { // added by Lumen (Stage 4A PR1-DI)
    input_text: payload.input_text, // added by Lumen (Stage 4A PR1-DI)
    normalized_number: normalized, // added by Lumen (Stage 4A PR1-DI)
    numerology_data: numerology, // added by Lumen (Stage 4A PR1-DI)
    chakra_data: chakra, // added by Lumen (Stage 4A PR1-DI)
  }; // added by Lumen (Stage 4A PR1-DI)
} // added by Lumen (Stage 4A PR1-DI)

export function isReadingPayload(value: unknown): value is ReadingPayload { // added by Lumen (Stage 4A PR1-DI)
  if (!value || typeof value !== "object") { // added by Lumen (Stage 4A PR1-DI)
    return false; // added by Lumen (Stage 4A PR1-DI)
  } // added by Lumen (Stage 4A PR1-DI)
  const record = value as Record<string, unknown>; // added by Lumen (Stage 4A PR1-DI)
  return typeof record.input_text === "string"; // added by Lumen (Stage 4A PR1-DI)
} // added by Lumen (Stage 4A PR1-DI)

export function handlerFactory(deps: Deps) { // added by Lumen (Stage 4A PR1-DI)
  return async function handler(req: Request): Promise<Response> { // added by Lumen (Stage 4A PR1-DI)
    const auth = deps.requireJwtHeader(req); // added by Lumen (Stage 4A PR1-DI)
    if (!auth.ok) { // added by Lumen (Stage 4A PR1-DI)
      const response: Result<never, ReadingErr> = { ok: false, error: { code: "UNAUTHORIZED", message: "Missing JWT" } }; // added by Lumen (Stage 4A PR1-DI)
      return new Response(JSON.stringify(response), { status: 401, headers: JSON_HEADERS }); // added by Lumen (Stage 4A PR1-DI)
    } // added by Lumen (Stage 4A PR1-DI)

    let payloadUnknown: unknown; // added by Lumen (Stage 4A PR1-DI)
    try { // added by Lumen (Stage 4A PR1-DI)
      payloadUnknown = await req.json(); // added by Lumen (Stage 4A PR1-DI)
    } catch { // added by Lumen (Stage 4A PR1-DI)
      const response: Result<never, ReadingErr> = { ok: false, error: { code: "BAD_REQUEST", message: "Invalid JSON payload" } }; // added by Lumen (Stage 4A PR1-DI)
      return new Response(JSON.stringify(response), { status: 400, headers: JSON_HEADERS }); // added by Lumen (Stage 4A PR1-DI)
    } // added by Lumen (Stage 4A PR1-DI)

    if (!isReadingPayload(payloadUnknown)) { // added by Lumen (Stage 4A PR1-DI)
      const response: Result<never, ReadingErr> = { ok: false, error: { code: "BAD_REQUEST", message: "Invalid payload" } }; // added by Lumen (Stage 4A PR1-DI)
      return new Response(JSON.stringify(response), { status: 400, headers: JSON_HEADERS }); // added by Lumen (Stage 4A PR1-DI)
    } // added by Lumen (Stage 4A PR1-DI)

    const payload = payloadUnknown as ReadingPayload; // added by Lumen (Stage 4A PR1-DI)

    try { // added by Lumen (Stage 4A PR1-DI)
      deps.ensureSupabaseClient(); // added by Lumen (Stage 4A PR1-DI)
    } catch (error) { // added by Lumen (Stage 4A PR1-DI)
      const response: Result<never, ReadingErr> = { ok: false, error: { code: "ENGINE_ERROR", message: error instanceof Error ? error.message : "Failed to initialize Supabase client" } }; // added by Lumen (Stage 4A PR1-DI)
      return new Response(JSON.stringify(response), { status: 500, headers: JSON_HEADERS }); // added by Lumen (Stage 4A PR1-DI)
    } // added by Lumen (Stage 4A PR1-DI)

    try { // added by Lumen (Stage 4A PR1-DI)
      const value = buildReading(payload); // added by Lumen (Stage 4A PR1-DI)
      const response: Result<ReadingOk, ReadingErr> = { ok: true, value }; // added by Lumen (Stage 4A PR1-DI)
      return new Response(JSON.stringify(response), { status: 200, headers: JSON_HEADERS }); // added by Lumen (Stage 4A PR1-DI)
    } catch (error) { // added by Lumen (Stage 4A PR1-DI)
      const response: Result<never, ReadingErr> = { ok: false, error: { code: "ENGINE_ERROR", message: error instanceof Error ? error.message : "Unknown error" } }; // added by Lumen (Stage 4A PR1-DI)
      return new Response(JSON.stringify(response), { status: 500, headers: JSON_HEADERS }); // added by Lumen (Stage 4A PR1-DI)
    } // added by Lumen (Stage 4A PR1-DI)
  }; // added by Lumen (Stage 4A PR1-DI)
} // added by Lumen (Stage 4A PR1-DI)
