import { serve } from "https://deno.land/std@0.168.0/http/server.ts"; // added by Lumen (Stage 4A PR1-DI)
import { createClient } from "https://esm.sh/@supabase/supabase-js@2"; // added by Lumen (Stage 4A PR1-DI)
import { withCors, requireJwt } from "../_shared/security.ts"; // added by Lumen (Stage 4A PR1-DI)
import { withTiming } from "../_shared/telemetry.ts"; // added by Lumen (Stage 4A PR1-DI)
import { handlerFactory } from "./handler.ts"; // added by Lumen (Stage 4A PR1-DI)

const handler = handlerFactory({ // added by Lumen (Stage 4A PR1-DI)
  requireJwtHeader: (req) => { // added by Lumen (Stage 4A PR1-DI)
    const jwt = requireJwt(req); // added by Lumen (Stage 4A PR1-DI)
    return jwt.ok ? { ok: true as const, token: jwt.token } : { ok: false as const }; // added by Lumen (Stage 4A PR1-DI)
  }, // added by Lumen (Stage 4A PR1-DI)
  ensureSupabaseClient: () => { // added by Lumen (Stage 4A PR1-DI)
    createClient( // added by Lumen (Stage 4A PR1-DI)
      Deno.env.get("SUPABASE_URL") ?? "", // added by Lumen (Stage 4A PR1-DI)
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "" // added by Lumen (Stage 4A PR1-DI)
    ); // added by Lumen (Stage 4A PR1-DI)
  }, // added by Lumen (Stage 4A PR1-DI)
}); // added by Lumen (Stage 4A PR1-DI)

serve(withCors(withTiming(handler))); // added by Lumen (Stage 4A PR1-DI)
