platform :ios, '13.0'
use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

project 'App/App.xcodeproj'

target 'App' do
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorCamera', :path => '../../node_modules/@capacitor/camera'
  pod 'CapacitorScreenReader', :path => '../../node_modules/@capacitor/screen-reader'
  pod 'SentryCapacitor', :path => '../../node_modules/@sentry/capacitor'

  target 'AppTests' do
    inherit! :search_paths
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
